<template>
	<div class="mainbox">
		<div class="titleBox">湖北省<span>2019年</span>医疗卫生情况
			<div class="buttons">下载</div>
		</div>
		<div class="modelDetailsBox">
			<div class="modelOneBox">
				<div class="modelboxs">
					<div class="levelTwoTitle"><span></span>卫生机构数
						<div class="buttonsBox">
							<div @click="modelOneChange(1)" :class="modelOneIndex==1?'choosen':''">医院</div>
							<div @click="modelOneChange(2)" :class="modelOneIndex==2?'choosen':''" style="width: 130px;">基层医疗卫生机构</div>
							<div @click="modelOneChange(3)" :class="modelOneIndex==3?'choosen':''" style="width: 130px;">专业公共卫生机构</div>
						</div>
					</div>
					<div style="width: 100%;height: calc(100% - 56px);">
						<div class="levelTwoechartsBoxs">
							<init-echartsthree :id='"memodelOneEchartsOne"' :datas = 'modelOneDataOne'></init-echartsthree>
						</div>
						<div class="levelTwoechartsBoxs">
							<init-echartstwo :id='"memodelOneEchartsTwo"' :datas = 'modelOneDataTwo'></init-echartstwo>
						</div>
					</div>
				</div>
			</div>
			
			<div class="modelTwoBox">
				<div class="modelboxs">
					<div class="levelTwoTitle"><span></span>卫生机构人员及床位数</div>
					<div style="width: 100%;height: calc(100% - 56px);">
						<div class="levelTwoechartsBoxs">
							<init-echartsone :id='"memodelTwoEchartsOne"' :datas = 'modelTwoDataOne'></init-echartsone>
						</div>
						<div class="levelTwoechartsBoxs">
							<init-echartsnine :id='"memodelTwoEchartsTwo"' :datas = 'modelTwoDataTwo'></init-echartsnine>
						</div>
					</div>
				</div>
			</div>
			
			<div class="modelThreeBox">
				<div class="modelboxs">
					<div class="levelTwoTitle"><span></span>主要城市卫生机构人员及床位数</div>
					<div style="width: 100%;height: calc(100% - 56px);">
						<div style="float: left;width: 40%;margin-left: 2%;height: 100%;">
							<init-echartsone :id='"memodelThreeEchartsOne"' :datas = 'modelThreeDataOne'></init-echartsone>
						</div>
						<div style="float: left;width: 50%;margin-left: 8%;height: 100%;">
							<map-echarts :id = '"memodelThreeEchartsTwo"' :datas = 'modelThreeDataTwo'></map-echarts>
						</div>
					</div>
				</div>
			</div>
			
			<div class="modelForeBox">
				<div class="modelboxs">
					<div class="levelTwoTitle"><span></span>农村村级卫生组织情况</div>
					<div style="width: 100%;height: calc(100% - 56px);">
						<div class="levelTwoechartsBoxs">
							<init-echartsone :id='"memodelForeEchartsOne"' :datas = 'modelForeDataOne'></init-echartsone>
						</div>
						<div class="levelTwoechartsBoxs">
							<init-echartsone :id='"memodelForeEchartsTwo"' :datas = 'modelForeDataTwo'></init-echartsone>
						</div>
					</div>
				</div>
			</div>
			
			<div class="modelFiveBox">
				<div class="modelboxs">
					<div class="levelTwoTitle"><span></span>医疗卫生机构情况</div>
					<div style="width: 100%;height: calc(100% - 56px);">
						<map-echarts :id = '"memodelFiveEchartsOne"' :datas = 'modelFiveDataOne'></map-echarts>
					</div>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
	import initEchartstwo from '../initEchartstwo.vue'
	import initEchartsone from '../initEchartsone.vue'
	import initEchartsthree from '../initEchartsthree.vue'
	import mapEcharts from '../mapEcharts.vue'
	import initEchartsnine from '../initEchartsnine.vue'
	export default{
		components:{initEchartsone,initEchartstwo,initEchartsthree,initEchartsnine,mapEcharts},
		data(){
			return{
				modelOneIndex:1,
				modelOneDataOne:{
					unit:'所',
					titles:'',
					nameList:['医院','综合医院','中西医院','专科医院'],
					dataListOne:[800, 700, 500, 432],
					color:['#ffd99d','#ffc66c']
				},
				modelOneDataTwo:{
					unit:'单位(所)',
					legendList:['卫生机构总计'],
					nameList:['2014','2015','2016','2017','2018'],
					dataListOne:[3500,3800,3400,4200,4300],
					color:['#80ebf5','#3dc5dd']
				},
				modelTwoDataOne:{
					unit:'单位(张)',
					legendList:['每千人口拥有医疗\n机构床位数','每千人口医生数'],
					nameList:['2014','2015','2016','2017','2018'],
					dataListOne:[500,600,700,500,800],
					dataListTwo:[100,200,100,200,200],
					color:['#80ebf5','#3dc5dd','#f0db4b','#fbeb81']
				},
				modelTwoDataTwo:{
					data:[{value:1234,name:'医院',selected:true},{value:1234,name:'乡镇卫生院'},{value:1234,name:'专业公共卫生机构'},{value:1234,name:'基层医疗卫生机构'}],
					unit:'张',
					title:'卫生机构床位\n数及分布',
					names:'卫生机构'
				},
				modelThreeDataOne:{
					unit:'单位(张)',
					legendList:['城镇每千人口拥有医疗机构床位数','乡村每千人口拥有医疗机构床位数'],
					nameList:['2014','2015','2016','2017','2018'],
					dataListOne:[500,600,700,500,800],
					dataListTwo:[100,200,100,200,200],
					color:['#487fff','#84a9ff','#80ebf5','#3dc5dd']
				},
				modelThreeDataTwo:{
					type:2,
					size:[0,1000],
					data : [
						{
							name:'武汉市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'恩施土家族苗族自治州',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'十堰市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'宜昌市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'襄阳市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'黄冈市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'荆州市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'荆门市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'咸宁市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'随州市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'孝感市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'黄石市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'神农架林区',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'天门市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'仙桃市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'潜江市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
						{
							name:'鄂州市',
							dataList:[
								{
									name:'基层医疗卫生人员数',
									value:'39001',
									unit:'人'
								},
								{
									name:'卫生技术人员数',
									value:'2209',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'22739',
									unit:'人'
								},
								{
									name:'注册护士数',
									value:'11930',
									unit:'人'
								},
							]
						},
					]
				},
				modelForeDataOne:{
					type:2, 
					unit:'单位(万人)',
					legendList:['乡村医生','卫生员'],
					nameList:['2014','2015','2016','2017','2018'],
					dataListOne:[500,600,700,500,800],
					dataListTwo:[100,200,100,200,200],
					color:['#487fff','#84a9ff','#80ebf5','#3dc5dd']
				},
				modelForeDataTwo:{
					unit:'单位(个)',
					legendList:['村设置的医疗点数','村均医疗点数'],
					nameList:['2014','2015','2016','2017','2018'],
					dataListOne:[500,600,700,500,800],
					dataListTwo:[100,200,100,200,200],
					color:['#487fff','#84a9ff','#ffc66d','#ffd89a']
				},
				modelFiveDataOne:{
					type:2,
					size:[0,1000],
					data : [
						{
							name:'武汉市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'恩施土家族苗族自治州',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'十堰市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'宜昌市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'襄阳市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'黄冈市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'荆州市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'荆门市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'咸宁市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'随州市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'孝感市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'黄石市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'神农架林区',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'天门市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'仙桃市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'潜江市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
						{
							name:'鄂州市',
							dataList:[
								{
									name:'机构数',
									value:'10000',
									unit:'个'
								},
								{
									name:'其中三级医院机构数',
									value:'5000',
									unit:'个'
								},
								{
									name:'床位数',
									value:'8000',
									unit:'张'
								},
								{
									name:'在岗职工数',
									value:'5000',
									unit:'人'
								},
								{
									name:'职业(助理)医师数',
									value:'8000',
									unit:'人'
								},
							]
						},
					]
				}
			}
		},
		mounted() {
			
		},
		methods:{
			modelOneChange(e){
				this.modelOneIndex = e;
			}
		}
	}
</script>

<style lang="less" scoped>
	.modelDetailsBox{
		width: 100%;
		height: auto;
		display: flex;
		flex-wrap: wrap;
		.modelOneBox{
			width: 746px;
			height: 332px;
			background: #fff;
			margin-bottom: 24px;
		}
		.modelTwoBox{
			width: 862px;
			height: 332px;
			background: #fff;
			margin-left: 32px;
			margin-bottom: 24px;
		}
		.modelThreeBox{
			width: 1632px;
			height: 433px;
			background: #fff;
			margin-bottom: 24px;
		}
		.modelForeBox{
			width: 798px;
			height: 430px;
			background: #fff;
			margin-bottom: 24px;
		}
		.modelFiveBox{
			width: 804px;
			height: 430px;
			margin-left: 32px;
			background: #fff;
			margin-bottom: 24px;
		}
	}
</style>
